---
monitoring_dir: /opt/monitoring
prometheus_scrape_interval: 15s
grafana_root_url: ""
grafana_image: grafana/grafana:11.6.4
node_exporter_image: quay.io/prometheus/node-exporter:v1.9.1
prometheus_image: prom/prometheus:v3.1.0
monitoring_textfile_dir: /var/lib/node_exporter
monitoring_alert_units:
  - nginx
  - docker
  - x-ui
