all:
  children:
    production:
      hosts:
        vps:
          ansible_host: "{{ vault_production_ip }}"
          ansible_port: "{{ vault_ssh_port }}"
          ansible_user: ubuntu
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
