all:
  children:
    lab:
      hosts:
        vm-test:
          ansible_host: 10.95.161.119
          ansible_port: 22
          ansible_user: ansible
    production:
      hosts:
        vps:
          ansible_host: YOUR_IP
          ansible_port: "{{ vault_ssh_port }}"
          ansible_user: ubuntu
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
